### ISSUE TITLE
Failed to activate the linter-sass-lint package

### ISSUE THREAD

**Issue by albertosramires** [AtomLinter/linter-sass-lint#44] opened 2016-02-17 01:51 UTC
**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [linter-sass-lint](https://github.com/AtomLinter/linter-sass-lint) package, v1.1.0

### Stack Trace

Failed to activate the linter-sass-lint package

```
At Cannot find module 'sb-callsite'

Error: Cannot find module 'sb-callsite'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.install (/Users/anubis/.atom/packages/linter-sass-lint/node_modules/atom-package-deps/lib/main.js:14:22)
    at Object.module.exports.activate (/Users/anubis/.atom/packages/linter-sass-lint/lib/main.coffee:35:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -3:52.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -3:50.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:33.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -3:31.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:31.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:31.5.0 project-find:show (atom-text-editor.editor.is-focused)
     -3:29.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  4x -3:26.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:21.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:21.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:14 pane:show-next-item (atom-text-editor.editor.is-focused)
     -1:16 core:copy (atom-text-editor.editor.is-focused)
     -1:15.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:14.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:32.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-gl-light-syntax.theme-one-light-ui)
     -0:23.2.0 pane:show-next-item (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-gl-light-syntax.theme-one-light-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-plus"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-light-ui",
      "gl-light-syntax"
    ]
  },
  "linter-sass-lint": {
    "configFile": "~/.atom/sass-lint.yml"
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.2.4
file-icons, v1.6.14
gl-light-syntax, v2.2.0
language-haml, v0.23.15
linter, v1.11.3
linter-bootlint, v1.0.0
linter-ruby, v1.2.1
linter-sass-lint, v1.1.0
linter-tidy, v2.1.0
minimap, v4.19.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-02-17 03:59
Looks like Atom failed to install all the modules, can you try uninstalling and installing the package?

**Comment by albertosramires** [comment] 2016-02-17 04:04
@Arcanemagus Just did, same error.

**Comment by Arcanemagus** [comment] 2016-02-17 04:48
Wait a sec... the package it can't find hasn't been a dependency of `atom-package-deps` since version 3.0.7, which should be too old to be being loaded by Atom :confused:

Do you have Node.js installed? If so can you run `npm list` in the package directory?

**Comment by C-Bouthoorn** [comment] 2016-02-17 13:52
Same on Atom Beta. Happens after the last update, worked fine before.


**Atom Version**: 1.6.0-beta3
**System**: Ubuntu 15.10
**Thrown From**: [linter-sass-lint](https://github.com/AtomLinter/linter-sass-lint) package, v1.1.0


### Stack Trace

Failed to activate the linter-sass-lint package

```
At Cannot find module 'sb-callsite'

Error: Cannot find module 'sb-callsite'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom-beta/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.install (/home/charlie/.atom/packages/linter-sass-lint/node_modules/atom-package-deps/lib/main.js:25:20)
    at Object.module.exports.activate (/home/charlie/.atom/packages/linter-sass-lint/lib/main.coffee:35:34)
    at Package.module.exports.Package.activateNow (/usr/share/atom-beta/resources/app.asar/src/package.js:181:20)
    at /usr/share/atom-beta/resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/usr/share/atom-beta/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom-beta/resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/usr/share/atom-beta/resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom-beta/resources/app.asar/src/package-manager.js:526:21)
    at /usr/share/atom-beta/resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/usr/share/atom-beta/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom-beta/resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -1:14.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-sharp-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "build-defaults",
      "tool-bar"
    ],
    "themes": [
      "seti-ui",
      "one-sharp-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.13.2
autocomplete-emojis, v2.2.2
autocomplete-html-entities, v0.1.0
autocomplete-love, v0.2.0
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-ruby, v0.1.0
build, v0.54.1
build-npm-apm, v0.8.0
color-picker, v2.1.1
java-importer, v1.4.1
language-c, v0.51.1
language-haskell, v1.5.2
language-lua, v0.9.4
language-r, v0.4.0
language-swift, v0.4.0
language-vbscript, v0.6.1
language-x86asm, v0.7.1
linter, v1.11.3
linter-alex, v2.0.0
linter-clang, v3.4.4
linter-coffeelint, v1.1.2
linter-cpplint, v1.0.1
linter-csslint, v1.3.1
linter-eslint, v6.0.0
linter-gcc, v0.6.5
linter-golinter, v1.2.0
linter-gotype, v0.1.0
linter-govet, v0.1.5
linter-hlint, v0.4.3
linter-htmlhint, v1.0.2
linter-javac, v1.5.0
linter-js-yaml, v1.2.5
linter-jshint, v2.0.0
linter-jsonlint, v1.1.5
linter-lintr, v1.0.4
linter-lua, v1.0.1
linter-lua-findglobals, v1.0.0
linter-markdown, v1.5.0
linter-php, v1.1.8
linter-pylint, v1.2.0
linter-ruby, v1.2.1
linter-sass-lint, v1.1.0
linter-scss-lint, v2.5.1
linter-shellcheck, v1.1.0
linter-swiftc, v2.0.0
linter-tidy, v2.1.0
linter-xmllint, v1.3.2
love-atom, v2.2.5
minimap, v4.19.0
minimap-linter, v1.1.1
one-sharp-syntax, v1.1.1
pigments, v0.24.1
seti-ui, v0.8.1

# Dev
No dev packages
```

And as @Arcanemagus requested:

`$ npm list`
```
/home/charlie
├─┬ cson@3.0.2
│ ├── coffee-script@1.10.0
│ ├── cson-parser@1.2.0
│ ├─┬ extract-opts@3.0.1
│ │ └── typechecker@2.1.0
│ ├── requirefresh@2.0.0
│ └─┬ safefs@4.0.0
│   └── graceful-fs@4.1.2
├─┬ eslint@1.10.1
│ ├─┬ chalk@1.1.1
│ │ ├── ansi-styles@2.1.0
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├─┬ strip-ansi@3.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ └── supports-color@2.0.0
│ ├─┬ concat-stream@1.5.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ readable-stream@2.0.4
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── isarray@0.0.1
│ │ │ ├── process-nextick-args@1.0.3
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ └── typedarray@0.0.6
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├─┬ doctrine@0.7.1
│ │ ├── esutils@1.1.6
│ │ └── isarray@0.0.1
│ ├── escape-string-regexp@1.0.3
│ ├─┬ escope@3.3.0
│ │ ├─┬ es6-map@0.1.3
│ │ │ ├── d@0.1.1
│ │ │ ├── es5-ext@0.10.8
│ │ │ ├── es6-iterator@2.0.0
│ │ │ ├── es6-set@0.1.3
│ │ │ ├── es6-symbol@3.0.1
│ │ │ └── event-emitter@0.3.4
│ │ ├─┬ es6-weak-map@2.0.1
│ │ │ ├── d@0.1.1
│ │ │ ├── es5-ext@0.10.8
│ │ │ ├── es6-iterator@2.0.0
│ │ │ └── es6-symbol@3.0.1
│ │ └─┬ esrecurse@3.1.1
│ │   └── estraverse@3.1.0
│ ├── espree@2.2.5
│ ├── estraverse@4.1.1
│ ├── estraverse-fb@1.3.1
│ ├── esutils@2.0.2
│ ├─┬ file-entry-cache@1.2.4
│ │ └─┬ flat-cache@1.0.10
│ │   ├─┬ del@2.1.0
│ │   │ ├─┬ globby@3.0.1
│ │   │ │ ├─┬ array-union@1.0.1
│ │   │ │ │ └── array-uniq@1.0.2
│ │   │ │ ├── arrify@1.0.0
│ │   │ │ └─┬ pinkie-promise@1.0.0
│ │   │ │   └── pinkie@1.0.0
│ │   │ ├── is-path-cwd@1.0.0
│ │   │ ├─┬ is-path-in-cwd@1.0.0
│ │   │ │ └── is-path-inside@1.0.0
│ │   │ ├── pify@2.3.0
│ │   │ ├─┬ pinkie-promise@2.0.0
│ │   │ │ └── pinkie@2.0.1
│ │   │ └── rimraf@2.4.4
│ │   ├── graceful-fs@4.1.2
│ │   ├─┬ read-json-sync@1.1.0
│ │   │ └── graceful-fs@3.0.8
│ │   └── write@0.2.1
│ ├─┬ glob@5.0.15
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ ├── inherits@2.0.1
│ │ └─┬ once@1.3.3
│ │   └── wrappy@1.0.1
│ ├── globals@8.12.1
│ ├─┬ handlebars@4.0.5
│ │ ├── async@1.5.0
│ │ ├─┬ optimist@0.6.1
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.3
│ │ ├─┬ source-map@0.4.4
│ │ │ └── amdefine@1.0.0
│ │ └─┬ uglify-js@2.6.1
│ │   ├── async@0.2.10
│ │   ├── source-map@0.5.3
│ │   ├── uglify-to-browserify@1.0.2
│ │   └─┬ yargs@3.10.0
│ │     ├── camelcase@1.2.1
│ │     ├─┬ cliui@2.1.0
│ │     │ ├─┬ center-align@0.1.2
│ │     │ │ ├─┬ align-text@0.1.3
│ │     │ │ │ ├─┬ kind-of@2.0.1
│ │     │ │ │ │ └── is-buffer@1.1.0
│ │     │ │ │ ├── longest@1.0.1
│ │     │ │ │ └── repeat-string@1.5.2
│ │     │ │ └── lazy-cache@0.2.4
│ │     │ ├─┬ right-align@0.1.3
│ │     │ │ └─┬ align-text@0.1.3
│ │     │ │   ├─┬ kind-of@2.0.1
│ │     │ │   │ └── is-buffer@1.1.0
│ │     │ │   ├── longest@1.0.1
│ │     │ │   └── repeat-string@1.5.2
│ │     │ └── wordwrap@0.0.2
│ │     ├── decamelize@1.1.1
│ │     └── window-size@0.1.0
│ ├─┬ inquirer@0.11.0
│ │ ├── ansi-escapes@1.1.0
│ │ ├── ansi-regex@2.0.0
│ │ ├─┬ cli-cursor@1.0.2
│ │ │ └─┬ restore-cursor@1.0.1
│ │ │   ├── exit-hook@1.1.1
│ │ │   └── onetime@1.0.0
│ │ ├── cli-width@1.1.0
│ │ ├── figures@1.4.0
│ │ ├── lodash@3.10.1
│ │ ├─┬ readline2@1.0.1
│ │ │ ├─┬ code-point-at@1.0.0
│ │ │ │ └── number-is-nan@1.0.0
│ │ │ ├─┬ is-fullwidth-code-point@1.0.0
│ │ │ │ └── number-is-nan@1.0.0
│ │ │ └── mute-stream@0.0.5
│ │ ├─┬ run-async@0.1.0
│ │ │ └─┬ once@1.3.3
│ │ │   └── wrappy@1.0.1
│ │ ├── rx-lite@3.1.2
│ │ ├── strip-ansi@3.0.0
│ │ └── through@2.3.8
│ ├─┬ is-my-json-valid@2.12.3
│ │ ├── generate-function@2.0.0
│ │ ├─┬ generate-object-property@1.2.0
│ │ │ └── is-property@1.0.2
│ │ ├── jsonpointer@2.0.0
│ │ └── xtend@4.0.1
│ ├─┬ is-resolvable@1.0.0
│ │ └── tryit@1.0.2
│ ├─┬ js-yaml@3.4.6
│ │ ├─┬ argparse@1.0.3
│ │ │ ├── lodash@3.10.1
│ │ │ └── sprintf-js@1.0.3
│ │ ├── esprima@2.7.0
│ │ └── inherit@2.2.2
│ ├─┬ json-stable-stringify@1.0.0
│ │ └── jsonify@0.0.0
│ ├─┬ lodash.clonedeep@3.0.2
│ │ ├─┬ lodash._baseclone@3.3.0
│ │ │ ├── lodash._arraycopy@3.0.0
│ │ │ ├── lodash._arrayeach@3.0.0
│ │ │ ├─┬ lodash._baseassign@3.2.0
│ │ │ │ └── lodash._basecopy@3.0.1
│ │ │ ├── lodash._basefor@3.0.2
│ │ │ ├── lodash.isarray@3.0.4
│ │ │ └─┬ lodash.keys@3.1.2
│ │ │   ├── lodash._getnative@3.9.1
│ │ │   └── lodash.isarguments@3.0.4
│ │ └── lodash._bindcallback@3.0.1
│ ├─┬ lodash.merge@3.3.2
│ │ ├── lodash._arraycopy@3.0.0
│ │ ├── lodash._arrayeach@3.0.0
│ │ ├─┬ lodash._createassigner@3.1.1
│ │ │ ├── lodash._bindcallback@3.0.1
│ │ │ ├── lodash._isiterateecall@3.0.9
│ │ │ └── lodash.restparam@3.6.1
│ │ ├── lodash._getnative@3.9.1
│ │ ├── lodash.isarguments@3.0.4
│ │ ├── lodash.isarray@3.0.4
│ │ ├─┬ lodash.isplainobject@3.2.0
│ │ │ └── lodash._basefor@3.0.2
│ │ ├── lodash.istypedarray@3.0.2
│ │ ├── lodash.keys@3.1.2
│ │ ├── lodash.keysin@3.0.8
│ │ └─┬ lodash.toplainobject@3.0.0
│ │   └── lodash._basecopy@3.0.1
│ ├─┬ lodash.omit@3.1.0
│ │ ├── lodash._arraymap@3.0.0
│ │ ├─┬ lodash._basedifference@3.0.3
│ │ │ ├── lodash._baseindexof@3.1.0
│ │ │ ├── lodash._cacheindexof@3.0.2
│ │ │ └─┬ lodash._createcache@3.1.2
│ │ │   └── lodash._getnative@3.9.1
│ │ ├─┬ lodash._baseflatten@3.1.4
│ │ │ ├── lodash.isarguments@3.0.4
│ │ │ └── lodash.isarray@3.0.4
│ │ ├── lodash._bindcallback@3.0.1
│ │ ├── lodash._pickbyarray@3.0.2
│ │ ├─┬ lodash._pickbycallback@3.0.0
│ │ │ └── lodash._basefor@3.0.2
│ │ ├─┬ lodash.keysin@3.0.8
│ │ │ ├── lodash.isarguments@3.0.4
│ │ │ └── lodash.isarray@3.0.4
│ │ └── lodash.restparam@3.6.1
│ ├─┬ minimatch@3.0.0
│ │ └─┬ brace-expansion@1.1.1
│ │   ├── balanced-match@0.2.1
│ │   └── concat-map@0.0.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── object-assign@4.0.1
│ ├─┬ optionator@0.6.0
│ │ ├── deep-is@0.1.3
│ │ ├── fast-levenshtein@1.0.7
│ │ ├── levn@0.2.5
│ │ ├── prelude-ls@1.1.2
│ │ ├── type-check@0.3.1
│ │ └── wordwrap@0.0.3
│ ├── path-is-absolute@1.0.0
│ ├── path-is-inside@1.0.1
│ ├── shelljs@0.5.3
│ ├── strip-json-comments@1.0.4
│ ├── text-table@0.2.0
│ ├─┬ user-home@2.0.0
│ │ └── os-homedir@1.0.1
│ └── xml-escape@1.0.0
├─┬ qunit@0.7.7
│ ├── argsparser@0.0.6
│ ├─┬ cli-table@0.3.1
│ │ └── colors@1.0.3
│ ├── co@3.1.0
│ ├─┬ istanbul@0.2.5
│ │ ├── abbrev@1.0.7
│ │ ├── async@0.2.10
│ │ ├─┬ escodegen@1.2.0
│ │ │ ├── esprima@1.0.4
│ │ │ ├── estraverse@1.5.1
│ │ │ ├── esutils@1.0.0
│ │ │ └─┬ source-map@0.1.43
│ │ │   └── amdefine@1.0.0
│ │ ├── esprima@1.1.0-dev-harmony (git://github.com/ariya/esprima.git#a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd)
│ │ ├─┬ fileset@0.1.8
│ │ │ ├─┬ glob@3.2.11
│ │ │ │ ├── inherits@2.0.1
│ │ │ │ └─┬ minimatch@0.3.0
│ │ │ │   ├── lru-cache@2.7.0
│ │ │ │   └── sigmund@1.0.1
│ │ │ └─┬ minimatch@0.4.0
│ │ │   ├── lru-cache@2.7.0
│ │ │   └── sigmund@1.0.1
│ │ ├─┬ handlebars@1.3.0
│ │ │ ├── optimist@0.3.7
│ │ │ └─┬ uglify-js@2.3.6
│ │ │   └─┬ source-map@0.1.43
│ │ │     └── amdefine@1.0.0
│ │ ├─┬ js-yaml@3.4.4
│ │ │ ├─┬ argparse@1.0.3
│ │ │ │ ├── lodash@3.10.1
│ │ │ │ └── sprintf-js@1.0.3
│ │ │ └── esprima@2.7.0
│ │ ├── mkdirp@0.3.5
│ │ ├── nopt@2.2.1
│ │ ├── resolve@0.6.3
│ │ ├── which@1.0.9
│ │ └── wordwrap@0.0.3
│ ├── qunitjs@1.10.0
│ ├── tracejs@0.1.8
│ └── underscore@1.8.3
└── xregexp@3.0.0
```

**Comment by DanPurdy** [comment] 2016-02-17 14:02
I can't recreate this locally, any idea @steelbrain @Arcanemagus I'm assuming there's a conflict with one of the other linter-pacakges using an outdated version of this module or something..

**Comment by steelbrain** [comment] 2016-02-17 14:11
@DanPurdy That's a very weird error, It would be nice to have some repro steps

**Comment by steelbrain** [comment] 2016-02-17 14:29
The fun part is that `lib/main.js` doesn't even exist anymore

**Comment by DanPurdy** [comment] 2016-02-17 14:44
:confused:

**Comment by C-Bouthoorn** [comment] 2016-02-17 16:42
Another update: I removed sb-callsite to debug this problem, and then it was gone. I did restart Atom in the meantime, so maybe that fixed it?

**Comment by Arcanemagus** [comment] 2016-02-17 17:39
@steelbrain @DanPurdy as I stated earlier, `sb-callsite` hasn't been a dependency of `atom-package-deps` since v3.0.7, and this package depends on `^4.0.1`. I think this must be yet _another_ instance of Atom completely failing at dependency management and updating :frowning:.

**Comment by DanPurdy** [comment] 2016-03-05 09:21
Going to close this as it looks like an apm issue and i've not been able to reproduce at all. Thanks everyone.

**Closed by DanPurdy** 2016-03-05 09:21 UTC
