### ISSUE TITLE
Crash when using quotes with the url() function

### ISSUE THREAD

**Issue by lemnis** [AtomLinter/linter-sass-lint#186] opened 2017-09-20 16:46 UTC
- Atom version: 1.20.1
- linter-sass-lint version: 1.8.0
- Global sass-lint version (if used): 1.11.1
- Platform:
  - [x] OSX
  - [ ] Windows
  - [ ] Linux

Also tested VS code v1.16.1 with Sass lint 0.0.4, and that worked as expected.

The window crashes when I try to add quotes to the `url()` function, I am trying to type:

```css
//sass-lint:disable-all

foo {
  bar: url("");
}
```

I didn't add my .sass-lint.yml, because it looks like the bug doesn't dependent on that.

**Comment by DanPurdy** [comment] 2017-09-25 22:57
Hi there, unfortunately this is a parser error in the gonzales-pe library. I added an issue https://github.com/tonyganch/gonzales-pe/issues/282 if you'd like to follow along. There's a fix ready to be released I believe that we will push into sass-lint and then this linter plugin as soon as is possible.

The sass-lint disable comments will have no effect unfortunately as they are post the file parsing.

**Comment by gorriecoe** [comment] 2017-10-03 03:45
Hey @lemnis, I have a temporary solution.   Just add this to  your snippets.cson.  It seems to parse fine with quotes added.
```
'.source.scss':
  'url':
    'prefix': 'url'
    'body': 'url(\'${1}\')'

```

**Comment by evolutionmedia** [comment] 2017-10-07 06:30
It's not really quotes, but brackets causing the issue. See GIFs here #190

**Comment by in-in** [comment] 2017-10-12 12:14
Any workaround for sass syntax?
It ruins my Atom so badly even if I copy/paste this `background-image: url()`

**Comment by lemnis** [comment] 2017-10-12 13:23
@in-in A small modification to @gorriecoe proposed workaround would work

```cson
'.source.sass':
  'url':
    'prefix': 'url'
    'body': 'url(\${1}\)'
```

Just make sure to press enter before typing a parenthesis

**Comment by DanPurdy** [comment] 2017-10-12 13:27
Hi everyone just an update that the issue is fixed in the AST upstream now, looking to getting it released in the next day or two so you'll be able to drop these workarounds, sorry for that!

**Comment by DanPurdy** [comment] 2017-10-17 07:48
This should be fixed now as we've made a fork of the AST and released that with the fixes temporarily to sass-lint which in turn meant i could update this plugin. Please let me know if it's not fixed.

**Closed by DanPurdy** 2017-10-17 07:48 UTC
Labels: AST upstream issue, bug
